json.id favorite.id
json.book_id favorite.book_id
json.user_id favorite.user_id
json.finished favorite.finished
json.rating favorite.rating
json.deadline favorite.deadline
json.on_page favorite.on_page
json.tracking favorite.tracking
json.progress favorite.progress
