# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7eed4dc19c014c5ab79be5e5406aac4ec895cac3fcdfd91fae98592a7f4f1f2ea544792811b4a9340e0716671838c8f533aa7d0fb2d1ae436a1504cb5c53b3b7

test:
  secret_key_base: 5142c9e8605e85a1392b6a25f9d6099cce18b6d99f6e4fedb06f5fa0b1bc08b1f68f0940d1aaac3d3008fb97a530808a314267a6776ad4d073eb2d839ca9fafb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
